### ISSUE TITLE
Running MRTK/Unity/Visual Studio/GitHub env. for all team member

### ISSUE THREAD

**Issue by MarvvanPal** [MarvvanPal/HydroShift#30]

**Comment by schilling-p** [comment]
Find out if error messages that arose are important:
1. "The only standalone target supported is Windows x64 with OpenXR. Other architectures and operating systems are not supported at this time."
2. "DllNotFoundException: MicrosoftOpenXRPlugin"

**Comment by schilling-p** [comment]
22.02.23 18:00 
As far as we can tell, the error messages are no problem.

**Comment by MarvvanPal** [comment]
All member share a working state in combination with unity and GitHub via own branches.
